server:
  port: 8102
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
spring:
  application:
    name: usian-order-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/usian?characterEncoding=UTF-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    cluster:
      nodes:
        - 192.168.220.136:7001
        - 192.168.220.136:7002
        - 192.168.220.136:7003
        - 192.168.220.136:7004
        - 192.168.220.136:7005
        - 192.168.220.136:7006
    jedis:
      pool:
        max-active: 20 #连接池最大连接数
        max-idle: 10 #连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.220.129
    port: 5672
    username: admin
    password: 1111
    virtual-host: /
    publisher-confirms: true #开启消息确认回调
    publisher-returns: true #开启消息退回回调


#订单
ORDER_ID_KEY: ORDER_ID_KEY #存进Redis中，用于订单ID 的key
ORDER_ID_BEGIN: 100544    #用redis的incr功能自增，从这个值开始子层
ORDER_ITEM_ID_KEY: ORDER_ITEM_ID_KEY #存进Redis中，用于订单商品详情ID 的key


#quartz集群分布式锁
SETNX_LOCK_ORDER_KEY: SETNX_LOCK_ORDER_KEY