spring:
  application:
    name: usian-search-web
  data:
    elasticsearch:
      cluster-nodes: 192.168.220.139:9200,192.168.220.140:9200

#索引名称
ES_INDEX_NAME: usian
#类型名称
ES_TYPE_NAME: item
server:
  port: 8096
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#全局配置
#请求连接的超时时间
ribbon:
  ConnectTimeout: 60000
  #请求处理的超时时间
  ReadTimeout: 60000


